#!/bin/bash
if [ $# -ne 1 ]; then
  # Print usage
  echo 'Error! wrong number of arguments'
  echo 'usage:'
  echo "$0 DESIRED_FIRST.DESIRED_SECOND.DESIRED_THIRD"
  echo 'e.g.'
  echo "$0 192.168.2"
  exit 1
fi

DESIRED_FIRST=$(echo $1|cut -f1 -d.)
DESIRED_SECOND=$(echo $1|cut -f2 -d.)
DESIRED_THIRD=$(echo $1|cut -f3 -d.)
: ${PARALLEL_JOBS=95}
if [ -e '/usr/bin/time' ]; then
THIS_TIME="/usr/bin/time -v"
else
THIS_TIME=time
fi

$THIS_TIME cut -f1 -d: /etc/trueuserdomains|parallel -j $PARALLEL_JOBS -n1 -I% $THIS_TIME ./ip_checker % ${DESIRED_FIRST}.${DESIRED_SECOND}.${DESIRED_THIRD}
