#!/bin/bash
if [ $# -ne 1 ]; then
  # Print usage
  echo 'Error! wrong number of arguments'
  echo 'usage:'
  echo "$0 DESIRED_FIRST.DESIRED_SECOND.DESIRED_THIRD"
  echo 'e.g.'
  echo "$0 192.168.2"
  exit 1
fi

DESIRED_FIRST=$(echo $1|cut -f1 -d.)
DESIRED_SECOND=$(echo $1|cut -f2 -d.)
DESIRED_THIRD=$(echo $1|cut -f3 -d.)

cut -f1 -d: /etc/trueuserdomains|xargs -n1 -I% ./cpanel_error_checker % ${DESIRED_FIRST}.${DESIRED_SECOND}.${DESIRED_THIRD}
