#!/bin/bash
if [ $# -ne 3 ]; then
  # Print usage
  echo 'Error! wrong number of arguments'
  echo 'usage:'
  echo "$0 DESIRED_FIRST DESIRED_SECOND DESIRED_THIRD"
  echo 'e.g.'
  echo "$0 192 168 2"
  exit 1
fi

DESIRED_FIRST=$1
DESIRED_SECOND=$2
DESIRED_THIRD=$3

cut -f1 -d: /etc/trueuserdomains|xargs -n1 -I% ./ip_checker % $DESIRED_FIRST $DESIRED_SECOND $DESIRED_THIRD
